# This file was *autogenerated* from the file sarkovskii.sage.
from sage.all_cmdline import *   # import sage library


x, mu, b    = var('x, mu, b');

def sarkovskii(f, the_var, verbose=False):
    print "Working with function f=="
    print f
    fixed_points = solve(f==the_var, the_var)
    print "f has", len(fixed_points), "fixed point(s):"
    if verbose:
        for pt in fixed_points:
            print pt

    period_two = solve(f(f)==the_var, the_var)
    if verbose:
        print "f has", len(period_two), "orbit(s) of period two."
    prime_period_two = [s for s in period_two if s not in fixed_points]
    print "f has", len(prime_period_two), "orbit(s) of prime period two."
    if verbose:
        for pt in prime_period_two:
            print pt

    period_three = solve(f(f(f))==the_var, the_var)
    if verbose:
        print "f has", len(period_three), "orbit(s) of period three."
    prime_period_three = [s for s in period_three if s not in period_two]
    print "f has", len(prime_period_three), "orbit(s) of prime period three."
    if verbose:
        for pt in prime_period_three:
            print pt

    if verbose:
        print "By sarkovskii's theorem, if f has an orbit of prime period"
        print " three, then f has orbits of every other prime period (and is"
        print " therefore chaotic)."


eq = Integer(2)**x
_=var("x,mu,b");f=symbolic_expression((e**(mu*x+b) - e**(-(mu*x+b)))/(e**(mu*x+b) + e**(-(mu*x+b)))).function(x,mu,b)
_=var("x,mu,b");f=symbolic_expression(e**(mu*x+b)).function(x,mu,b)
_=var("x,mu,b");f=symbolic_expression((mu*x+b)**Integer(2)).function(x,mu,b)
sarkovskii(f, x, True)

